<section id="gallery" class="section-padding bg-background">
    <div class="ast-container">
        <h2 class="font-display text-3xl md:text-4xl font-bold text-primary mb-4 text-center">Egyptian Limestone Project Gallery</h2>
        <p class="font-body text-foreground/70 text-center max-w-2xl mx-auto mb-12">Explore projects showcasing the versatility and beauty of Egyptian limestone worldwide.</p>
        <div class="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-4">
            <div class="overflow-hidden rounded-lg cursor-pointer group md:col-span-2 md:row-span-2"><img src="<?php echo get_stylesheet_directory_uri(); ?>/frontend/assets/gallery-1.jpg" alt="Grand mosque exterior built with Egyptian limestone cladding" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 min-h-[150px]" loading="lazy" width="671" height="503"></div>
            <div class="overflow-hidden rounded-lg cursor-pointer group "><img src="<?php echo get_stylesheet_directory_uri(); ?>/frontend/assets/gallery-2.jpg" alt="Modern residential villa with Egyptian limestone exterior walls" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 min-h-[150px]" loading="lazy" width="327" height="327"></div>
            <div class="overflow-hidden rounded-lg cursor-pointer group "><img src="<?php echo get_stylesheet_directory_uri(); ?>/frontend/assets/application-hotel.jpg" alt="Luxury hotel lobby with Egyptian limestone flooring" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 min-h-[150px]" loading="lazy" width="327" height="327"></div>
            <div class="overflow-hidden rounded-lg cursor-pointer group md:col-span-2 md:row-span-2"><img src="<?php echo get_stylesheet_directory_uri(); ?>/frontend/assets/gallery-3.jpg" alt="Luxury shopping mall interior with Egyptian limestone flooring" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 min-h-[150px]" loading="lazy"></div>
            <div class="overflow-hidden rounded-lg cursor-pointer group "><img src="<?php echo get_stylesheet_directory_uri(); ?>/frontend/assets/application-facade.jpg" alt="Commercial building with Egyptian limestone facade" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 min-h-[150px]" loading="lazy" width="671" height="503"></div>
            <div class="overflow-hidden rounded-lg cursor-pointer group "><img src="<?php echo get_stylesheet_directory_uri(); ?>/frontend/assets/gallery-4.jpg" alt="Egyptian limestone blocks stacked at quarry ready for export" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 min-h-[150px]" loading="lazy" width="327" height="327"></div>
            <div class="overflow-hidden rounded-lg cursor-pointer group "><img src="<?php echo get_stylesheet_directory_uri(); ?>/frontend/assets/application-outdoor.jpg" alt="Outdoor terrace with Egyptian limestone paving" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 min-h-[150px]" loading="lazy" width="327" height="327"></div>
            <div class="overflow-hidden rounded-lg cursor-pointer group "><img src="<?php echo get_stylesheet_directory_uri(); ?>/frontend/assets/gallery-5.jpg" alt="Modern office lobby with Egyptian limestone reception desk" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 min-h-[150px]" loading="lazy" width="327" height="327"></div>
            <div class="overflow-hidden rounded-lg cursor-pointer group "><img src="<?php echo get_stylesheet_directory_uri(); ?>/frontend/assets/gallery-6.jpg" alt="Luxury villa pool area with Egyptian limestone paving" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 min-h-[150px]" loading="lazy" width="327" height="327"></div>
            <div class="overflow-hidden rounded-lg cursor-pointer group "><img src="<?php echo get_stylesheet_directory_uri(); ?>/frontend/assets/gallery-7.jpg" alt="Museum interior with Egyptian limestone walls" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700 min-h-[150px]" loading="lazy" width="327" height="327"></div>
        </div>
    </div>
</section>